### Get all images
GET http://localhost:3003 HTTP/1.1

### Add new comment
POST http://localhost:3003/comment/add HTTP/1.1
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZm9vQGZvby5jb20iLCJpYXQiOjE2ODI1ODA1Nzl9.x67VChnLOHJ4ISjp4FNhNis2ZWJLZmp4XjrbCkFCQVw
Content-Type: application/json

{
  "text": "This is test comment from Rest client",
  "image_id": 4,
  "user_id":1
}

### Add new comment using invalid token
POST http://localhost:3003/comment/add HTTP/1.1
Cookie: access_token=foo
Content-Type: application/json

{
  "text": "This is test comment from Rest client",
  "image_id": 4,
  "user_id":1
}

### Add new comment
POST http://localhost:3003/login HTTP/1.1
Content-Type: application/json

{
  "email": "foo@foo.com",
  "password": "abc123"
}

